name: Backmerge main -> next

on:
    push:
        branches:
            - 'main'

jobs:
    backmerge:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  persist-credentials: false

            - name: Merge main -> next
              uses: devmasx/merge-branch@v1.4.0
              with:
                  type: now
                  from_branch: main
                  target_branch: next
                  github_token: ${{ secrets.GITHUB_TOKEN  }}
                  message: "Merge 'main' into 'next' [skip ci]"
