name: Benchmarks

on:
    - push
    - pull_request

jobs:
    benchmark_current:
        name: benchmark current
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  ref: ${{ github.base_ref }}
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: lts/*
            - name: Install dependencies
              run: npm i
            - name: Run Benchmark
              run: npm run bench

    benchmark_branch:
        name: benchmark branch
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: lts/*
            - name: Install dependencies
              run: npm i
            - name: Run Benchmark
              run: npm run bench
